# The current drawback of this workflow is that it cannot auto update the current rust version
# This should be fixed in the future
# We don't run rustup install(s) from this script to avoid excess disk writes lowering the life of our Mac's
# NVMe

kind: pipeline
type: ssh
name: Run tests on M1

server:
  host:
    from_secret: host
  user:
    from_secret: user
  password:
    from_secret: password

steps:
- name: Setup rust and test
  environment:
    SRCENV:
      from_secret: srcenv
  commands:
    - source $SRCENV/.cargo/env
    - export RUSTUP_HOME=$SRCENV/.rustup
    - cargo test --verbose
