# This workflow doesn't support cache invalidation for unused dependencies at the moment

kind: pipeline
type: ssh
name: Build on M1

server:
  host:
    from_secret: host
  user:
    from_secret: user
  password:
    from_secret: password

steps:
  - name: Update rust
    commands:
      - /usr/local/bin/rustup-update
  - name: Run tests
    commands:
      - make test
    when:
      event:
        exclude:
          - tag
  - name: Build bundle
    environment:
      TARGET: aarch64-apple-darwin
      VERSION: ${DRONE_TAG}
      ARTIFACT: aarch64-apple-darwin
      TOOLDIR:
        from_secret: tooldir
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - make bundle
      - $TOOLDIR/hub release edit $($TOOLDIR/gfind . -type f -name "*.zip" -printf "-a %p ") -m "" "$VERSION"
    when:
      event:
        - tag
