[workspace]
resolver = "1"
members = ["cli", "server", "libsky", "sky-bench", "sky-macros", "harness"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
strip = "debuginfo"

[patch.crates-io]
cc = { git = "https://github.com/rust-lang/cc-rs" }