#!/bin/sh -e

if [ $1 = "install" ]; then
    systemctl enable skyd
    systemctl start skyd
fi

if [ $1 = "upgrade" ]; then
    echo "Upgrade complete. Stopping and restarting process ..."
    systemctl daemon-reload
    systemctl stop skyd
    systemctl start skyd
fi

#DEBHELPER#